### ISSUE TITLE
LCDExample.java doesn't work in released 1.1

### ISSUE THREAD

**Issue by Dumasen** [Pi4J/pi4j-v1#275] opened 2016-09-20 12:28 UTC
Hi!

I tried to use LCDExample.java, but I got a fatal error: wiringPiSetup*: you must only call this once per program run. This is a fatal error. Please fix your code.

I think this error is caused by two times called GpioFactory.getInstance() in one running: the first is final GpioController gpio = GpioFactory.getInstance(), the other is final GpioLcdDisplay lcd = new GpioLcdDisplay(...). 

 If I  comment final GpioController gpio = GpioFactory.getInstance(); (and other gpio using) line, the code works fine, and the the 16*2 Display writes everything.

 I have to use very simular working in my project: LCD Display and Input/Output must be worked same time.

Somebody could help me solving this problem, maybe give me a workaround solution for it. 

Best,
   Dumasen

**Comment by savageautomate** [comment] 2016-12-02 16:09
Duplicate of #278; Fixed in latest 1.2-SNAPSHOT build.

**Closed as completed by savageautomate** 2016-12-02 16:09 UTC
Labels: duplicate
